name: Build UPSC PDF

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc + LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-latex-extra

      - name: Show files
        run: ls -la

      - name: Generate PDF
        run: pandoc ./notes.md -o UPSC_OnePager_Notes.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: UPSC-PDF
          path: UPSC_OnePager_Notes.pdf
